# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@os-eco/seeds-cli@0.2.5" = fetchurl {
    url = "https://registry.npmjs.org/@os-eco/seeds-cli/-/seeds-cli-0.2.5.tgz";
    hash = "sha512-kqpsZYh2ZqFwxLWF726VmpVcKLb1nQzy1z0ucY8elqt5u0GHmPk+5EyZqo6QlmeAmujOY0HN+JskYmQmGRoQYQ==";
  };
  "@types/bun@1.3.10" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.10.tgz";
    hash = "sha512-0+rlrUrOrTSskibryHbvQkDOWRJwJZqZlxrUs1u4oOoTln8+WIXBPmAuCF35SWB2z4Zl3E84Nl/D0P7803nigQ==";
  };
  "@types/node@25.5.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.5.0.tgz";
    hash = "sha512-jp2P3tQMSxWugkCUKLRPVUpGaL5MVFwF8RDuSRztfwgN1wmqJeMSbKlnEtQqU8UrhTmzEmZdu2I6v2dpp7XIxw==";
  };
  "bun-types@1.3.10" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.10.tgz";
    hash = "sha512-tcpfCCl6XWo6nCVnpcVrxQ+9AYN1iqMIzgrSKYMB/fjLtV2eyAVEg7AxQJuCq/26R6HpKWykQXuSOq/21RYcbg==";
  };
  "bun2nix@2.0.8" = fetchurl {
    url = "https://registry.npmjs.org/bun2nix/-/bun2nix-2.0.8.tgz";
    hash = "sha512-pwq35hA81X1Kjsi5Xo69Aii9aY3zZHhWXwqF1QRz/uB35KzKbwJZ16WrhadiG9/T6bjOsRrPZtzuAyqmlXopLw==";
  };
  "chalk@5.6.2" = fetchurl {
    url = "https://registry.npmjs.org/chalk/-/chalk-5.6.2.tgz";
    hash = "sha512-7NzBL0rN6fMUW+f7A6Io4h40qQlG+xGmtMxfbnH/K7TAtt8JQWVQK+6g0UXKMeVJoyV5EkkNsErQ8pVD3bLHbA==";
  };
  "commander@14.0.3" = fetchurl {
    url = "https://registry.npmjs.org/commander/-/commander-14.0.3.tgz";
    hash = "sha512-H+y0Jo/T1RZ9qPP4Eh1pkcQcLRglraJaSLoyOtHxu6AapkjWVCy2Sit1QQ4x3Dng8qDlSsZEet7g5Pq06MvTgw==";
  };
  "mri@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
    hash = "sha512-tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
  };
  "sade@1.8.1" = fetchurl {
    url = "https://registry.npmjs.org/sade/-/sade-1.8.1.tgz";
    hash = "sha512-xal3CZX1Xlo/k4ApwCFrHVACi9fBqJ7V+mwhBsuf/1IOKbBy098Fex+Wa/5QMubw09pSZ/u8EY8PWgevJsXp1A==";
  };
  "undici-types@7.18.2" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.18.2.tgz";
    hash = "sha512-AsuCzffGHJybSaRrmr5eHr81mwJU3kjw6M+uprWvCXiNeN9SOGwQ3Jn8jb8m3Z6izVgknn1R0FTCEAP2QrLY/w==";
  };
}
